### ISSUE TITLE
Investigate why mysql server closes connection intermittently

### ISSUE THREAD

**Issue by jrynhart** [dulibrarytech/collections-as-data-api#7]
Error: Connection lost: The server closed the connection.
1|cad-api  |     at Protocol.end (/home/appuser/collections-as-data-api/node_modules/mysql/lib/protocol/Protocol.js:112:13)
1|cad-api  |     at Socket.<anonymous> (/home/appuser/collections-as-data-api/node_modules/mysql/lib/Connection.js:94:28)
1|cad-api  |     at Socket.<anonymous> (/home/appuser/collections-as-data-api/node_modules/mysql/lib/Connection.js:526:10)
1|cad-api  |     at Socket.emit (events.js:203:15)
1|cad-api  |     at Socket.EventEmitter.emit (domain.js:448:20)
1|cad-api  |     at endReadableNT (_stream_readable.js:1145:12)
1|cad-api  |     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by jrynhart** [comment]
https://stackoverflow.com/questions/14087924/cannot-enqueue-handshake-after-invoking-quit

Server is apparently disconnection. Do not need to maintain an open connection with the CAD application. Updated to open a new connection with each request, then close the connection after.
